### ISSUE TITLE
PID - Safety Checks

### ISSUE THREAD

**Issue by kushagharahi** [Pearcerobotics/FRC2018#1]
As a robotics student I want parts controlled by a PID loop to be safe. Here are the safety requirements I would like on each PID loop:

Min/Max Current
Min/Max Temp
Min/Max Speed 
Normal Operating Current
Normal Operating Temp
Normal Operating Speed
Safety Override - Something to override the max values
Manual Override - Disable PID loop, and manually move stuff without sensors

**Comment by Stuart1745** [comment]
Moved to 2019 Repo
https://github.com/Pearcerobotics/FRC2019/issues/11

**Comment by Stuart1745** [comment]
should this be in each of the systems classes or should we do one P-51 controller/safety class that each of the systems inherit from?
