### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by kushagharahi** [Pearcerobotics/FRC2018#10]
As a robotics student that is interested in getting started, I need a README.md created that tells me:

- Introduction, what are these files and code I'm looking at?!
- Getting Started, what the heck do I need to download and install???
- How to Build - ok I wrote some code how do I make it into something the robot can understand?
- How to Deploy - I've built my code, how do I get it onto the robot?
- Pull request guidelines - My codes build is passing, I've made sure it still builds/compiles, I've wrote tests to ensure my code works, existing tests still pass (I haven't broken anything existing), and all my code is pushed to a feature branch. How the heckers do I get my code into the main repository?

Essentially, the README.md should be a one stop shop for a developer to be able to get started and productive without having to do their own research (besides how to program)

**Comment by kushagharahi** [comment]
This is not quite as detailed as I would like it but it's a good start if you need a reference:
https://github.com/Team254/FRC-2018-Public/blob/master/README.md

**Comment by Stuart1745** [comment]
Moved to 2019 Repo
https://github.com/Pearcerobotics/FRC2019/issues/3
