### ISSUE TITLE
Dashboard | Front end - MVP

### ISSUE THREAD

**Issue by kushagharahi** [Pearcerobotics/FRC2018#2]
As a robot driver/operator I would like to have a dashboard

Get a basic dashboard on our control system running using: https://github.com/FRCDashboard/FRCDashboard

**Comment by kushagharahi** [comment]
Good info: https://3.basecamp.com/3782372/buckets/7420091/messages/1376098723

**Comment by Stuart1745** [comment]
Moved to 2019 Repo
https://github.com/Pearcerobotics/FRC2019/issues/10
