### ISSUE TITLE
Robot - Tests

### ISSUE THREAD

**Issue by kushagharahi** [Pearcerobotics/FRC2018#6]
As a robotics developer, I would like to have tests that prove I haven't broken anything when there are new additions

- Add tests for existing code

**Comment by kushagharahi** [comment]
Since this is Java - JUnit? https://junit.org/junit5/

**Comment by kushagharahi** [comment]
👀 https://github.com/Team254/FRC-2018-Public/tree/master/src/test

**Comment by Stuart1745** [comment]
Moved to 2019 Repo
https://github.com/Pearcerobotics/FRC2019/issues/2
