### ISSUE TITLE
Package management system

### ISSUE THREAD

**Issue by kushagharahi** [Pearcerobotics/FRC2018#8]
As a robotics developer I would like a packaging system so I can create reusable shared packages for reusability

Use Gradle (couldn't find maven): https://github.com/wpilibsuite/GradleRIO

**Comment by kushagharahi** [comment]
Also all these packages in bin/jar need to go and instead be managed via Gradle for easy upgradability and management. Let's get rid of ANT

**Comment by Stuart1745** [comment]
so Gradle will be the default in the 2019 season. 
Ant is Dead
https://www.firstinspires.org/robotics/frc/blog/2019-wpilib

**Comment by Stuart1745** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change Her Majesty to a Test Platform for Code](https://trello.com/c/S9dyrWZk/4-change-her-majesty-to-a-test-platform-for-code)

**Comment by Stuart1745** [comment]
@kushagharahi since Gradle is the default for 2019 should re remove this?
